params: scan_directory=CHANGEME token=CHANGEME project_key=CHANGEME url=CHANGEME output_directory=CHANGEME
steps:
  - name: Secret Scan with detect-secrets
    command: detect-secrets -C ${scan_directory} scan
    stdout: ${output_directory}/secrets.json

  - name: Vulnerability Scan with Bandit
    command: bash
    script: bandit -r -f json -o ${output_directory//\"}/bandit_result.json ${scan_directory} || true
    depends:
    - Secret Scan with detect-secrets

  - name: Vulnerability Scan with Grype
    command: sudo grype dir:${scan_directory} -o json --file ${output_directory}/grype.json
    depends:
    - Vulnerability Scan with Bandit

  # Safety tool now requires an account in their platform.
  # Run `safety auth login` command to login or register before running this step.
  - name: Dependency Scan with Safety
    command: safety check --continue-on-error --save-json ${output_directory}/safety.json
    depends:
    - Vulnerability Scan with Grype

  - name: Dependency Scan with OWASP Dependency Check
    command: dependency-check --scan \"${scan_directory}\" --out ${output_directory}
    depends:
    - Dependency Scan with Safety

  - name: SBOM Generation With Syft
    command: syft ${scan_directory} --output cyclonedx-json 
    stdout: ${output_directory}/sbom.json
    depends:
    - Dependency Scan with OWASP Dependency Check

  # This step requires a configured instance of SonarQube with a desired project.
  # 
  # After the configuration on SonarQube, you must add the required parameters below to perform your scan.
  # Also, you must use a SonarScanner CLI instance. Command below will run the container image of the instance.
  # This step and its commands are specified for Python projects.
  # You can see the scan results on SonarQube UI.
  - name: SAST Scan with SonarQube
    run: devsecops-atomic-sonarqube-other.yaml
    params: scan_directory=$scan_directory token=$token project_key=$project_key url=$url
    depends: 
    - SBOM Generation With Syft


  # This step is an alternative to one above.
  # This step uses Snyk tool to conduct a SAST scan.
  # Before running this step, make sure that you have a Snyk account and Snyk CLI installed in your device,
  # run `snyk auth` command and enable Snyk Code in your Snyk account.
  - name: SAST Scan with Snyk
    run: devsecops-atomic-snyk.yaml
    params: scan_directory=${scan_directory} output_directory=${output_directory}    
    depends: 
    - SBOM Generation With Syft
