params: scan_directory=CHANGEME output_directory=CHANGEME
steps:  
  - name: Secret Scan with Detect Secrets
    command: "detect-secrets -C ${scan_directory} scan"
    stdout: ${output_directory}/secrets.json

  - name: Vulnerability Scan with Grype
    command: "sudo grype dir:${scan_directory} -o json --file ${output_directory}/grype.json"
    depends:
    - Secret Scan with Detect Secrets

  - name: Dependency Scan with OWASP Dependency Check
    command: "dependency-check/bin/dependency-check.sh --scan \"${scan_directory}\" --out ${output_directory}"
    depends:
    - Vulnerability Scan with Grype

  - name: SBOM Generation With Syft
    command: syft ${scan_directory} --output cyclonedx-json
    stdout: ${output_directory}/sbom.json
    depends:
    - Dependency Scan with OWASP Dependency Check

  # This step requires a configured instance of SonarQube with a desired project.
  # 
  # After the configuration on SonarQube, you must add the required parameters below to perform your scan.
  # This step and its commands are specified for Java projects.
  # You can see the scan results on SonarQube UI.
  - name: SAST Scan with SonarQube
    dir: ${scan_directory}
    command: bash
    script: |
      mvn clean verify sonar:sonar \
        -Dsonar.projectKey=java \
        -Dsonar.projectName='java' \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.token=sqp_6ab84ccf0b0e718d5e084faf973434a8a768dfac
    depends: 
    - SBOM Generation With Syft